### ISSUE TITLE
TE: Search trigger

### ISSUE THREAD

**Issue by Joey79100** [MontyTRC89/Tomb-Editor#417]
This is not the same thing as #358 , this is related to #416 though:

NGLE had several ways of searching triggers. One is similar to TE, it works by typing some words used in the descriptions.
The other was to use `Find trigger number` button, that allowed several ways:
- [x] using short name, like "F192" to search for flipeffect with ID 192. As explained in #416, it's very common to refer to trigger with their short name.
- [x] using the exported trigger, like "$2000, 373, $1" - this is more complete, because it doesn't just search for the trigger but also fills all parameters (timer, extra). It's really useful when trying to find what an exported trigger used in scripts was (so we don't have to always paste the whole big comment, and keep only the relevant info in the script)
- [ ] using the AnimCommand values. This is for triggers exported as AnimCommands, but TE doesn't support this, and it is not used as much as the 2 others so it's definitely not a priority.

![image](https://user-images.githubusercontent.com/12445716/67158996-59682f00-f33f-11e9-86b4-01181786ef70.png)

![image](https://user-images.githubusercontent.com/12445716/67158990-50775d80-f33f-11e9-9851-184213e41996.png)

**Comment by Lwmte** [comment]
Unable to implement 3 because of inconsistent TRNG format parsing, so closing this issue.
