### ISSUE TITLE
TIDE: Add TR1-5 Engine Types support to TombIDE

### ISSUE THREAD

**Issue by Castigavi** [MontyTRC89/Tomb-Editor#479]
**Summary:**
Tomb Editor now allows using TR1-3 engines to create levels. Moreover it even has TR5/TR5Main experimental support. That being said TombIDE still doesn't support them. It should at least support the officially supported and fully working TR1-3 engines as well.

I have created packages that could be used as a base for TR1-3 projects:
https://drive.google.com/drive/folders/1kqIitYx9AzVCveoF34ArcswCirUrf_uw?usp=sharing
Due to Google Drive thinking TR is bad I had to set password to each archive. Password is: 1

TR1 has both TombATI and software executable for those with modern and older hardwares.
TR2 uses tr2main.
TR3 uses normal TR3 executable, but patched to work on modern systems and to support widescreen resolutions. Unfortunately this one is big because it has entire music package included with no way to replace it with something else.

**Comment by Nickelony** [comment]
Done.
