### ISSUE TITLE
TIDE: Shortcut to create INCLUDE files

### ISSUE THREAD

**Issue by Joey79100** [MontyTRC89/Tomb-Editor#483]
NG Center allows you, anywhere in the script, to create and include a file.
Put your cursor anywhere, press Ctrl+F5: it asks for the name, then creates the file and puts the #INCLUDE directive in the script.

Unless I'm mistaken TombIDE doesn't have a way to quickly create those files.

For **new files**, it could be: _right clicking somewhere on the script_, and clicking an _option in the contextual menu_. Plus a keyboard shortcut.
For **existing files** (ie. the file already exists in the script folder, you can see it in the file list, but you want to include it in a new level), we could _drag the file from the file list_, and _drop it somewhere in the script_.

**Comment by Nickelony** [comment]
Done, but without the smart autocomplete I mentioned.
