### ISSUE TITLE
TIDE: Issues reported on TRF

### ISSUE THREAD

**Issue by Lwmte** [MontyTRC89/Tomb-Editor#524]
- [x] Script bookmarks aren't detected as changes, so we can't save them. (AkyV)
- [x] `#FIRST_ID` doesn't work in `#INCLUDE` subscripts. If I type the command name after `#FIRST_ID` directive, and then the equals sign (as I should), TIDE says it is an invalid command. (AkyV)
- [ ] Pressing F1 should fill in the next triggergroup ID, correct? In my case, TombIDE seems to hang for several minutes, then add what is definitely not the next available ID. For example, 92 is the next, but TombIDE sets it as 290. Is this just a problem with very large scripts? (Justin)
- [x] "Level Name" slots don't get a "NULL" tag when I delete the old (removed) level name there, leaving that string empty.
Now the strings jump one upside, to fill that empty string, so the hardcoded string positions will be removed from their place. (AkyV)
- [x] About TIDE TRNG/TRLE Mnemonic constant function, i.e. the cursor above the constant, and the message says to hit F12:
- not detected if it is typed in a hexadecimal form,
- not detected if it is typed in a decimal form, plus, portrayed as not a mnemonic constant (i.e. not purple but orange),
- if they are added to each other with + signs, then it wants to open the help file for all - which it naturally can't,
- in Plugin commands Plugin names detected badly, by that message, as a mnemonic constant,
- there is no F12 for simple constants like ENABLED, IGNORE etc. It is acceptable, I mean why would I open an empty help file? On the other hand, if I type the constant for these values in a (hexa)decimal form, then that may be an error in the compilation. (Eg. Horizon= 1.) (AkyV)

**Comment by Nickelony** [comment]
Closing. Last checkbox moved to another issue.
