### ISSUE TITLE
TE: Invalid texture pages data written in compiled .tr4 file

### ISSUE THREAD

**Issue by LoreRaider** [MontyTRC89/Tomb-Editor#526]
There's been an issue for almost 2 years now where apparently Tomb Editor texture packer writes an invalid texture page ID on levels with a big amount of texinfos (from around 7500/8000 to above) which either makes the game crash randomly in different spots of the map or shows corrupted textures on geometry and objects, and "moves" around randomly by any changes you make in the map itself.
It's also pretty much trial and error if you want to avoid this without twisting the level too much to make it work (meaning to drastically decrease the number of texinfos).

I and ChocolateFan have been investigating this thanks to a plugin that she wrote for me, which shows a list of the current texture pages loaded in that specific frame of the game.
At the moment of the crash, the log shows the page ID 2047 which is completely out of range from the texture pages list on the level I tested it (which is 175), and so the engine tries to read this but can't find anything, leading to an instant crash.

In the package I provided textures files, one .wad2 and 2 projects with 2 different .wad files, one project with a wad where the level crashes instantly ingame right after level loading, meanwhile the second project with a wad (with vanilla TR4 lara_skin, lara_skin_joints, lara_scream) where textures are corrupted ingame.

An example of screenshot ingame with corrupted textures using the 2nd wad (vanilla TR4 lara)
![image](https://user-images.githubusercontent.com/48493527/149970030-38be96e1-f1c3-4828-9e0b-7f0df651e063.png)

Link: https://drive.google.com/file/d/1S7FnBbXenaGSt3P2PUqb5Sv1KWT3UQgq/view?usp=sharing
Sounds used: https://drive.google.com/file/d/1JbeCN53tF8zlNNRV8B_wxL-2bjYvfxMO/view?usp=sharing

Repro steps:
-open one of the projects and connect all the textures files and wad if needed
-compile the level and run with any script (even vanilla TRLE) selecting the 2nd level entry

As an optional thing, I will also include ChocolateFan plugin in case it's useful to investigate this problem
[PlugIn_trng.zip](https://github.com/MontyTRC89/Tomb-Editor/files/7890254/PlugIn_trng.zip)

Steps to make the plugin work:
-unzip the package above and copy PlugIn_trng.dll inside a playable TRNG folder
-run TOMB4_LOG.exe and right after run tomb4.exe
-pages will start popping up on the log, at the moment of the crash, the log should say "page=2047"

**Comment by Lwmte** [comment]
TE does not write corrupted data into .tr4 file. This is tomb4 issue.
