### ISSUE TITLE
Imported Geometry (MQO) Texture Placement

### ISSUE THREAD

**Issue by MatieTR** [MontyTRC89/Tomb-Editor#537]
Exporting a room in .mqo and importing it looks fine in editor, but textures are messed up in-game, issue was present in 1.4.6 and is still present in 1.4.7.

Editor image with imported geo placed in the room, textures look perfectly fine:

![Untitled](https://user-images.githubusercontent.com/48183219/153727184-bd19a838-c200-404c-81c7-c5b9804fa4ac.jpg)

In-game picture with textures missing and overlapping. The water texture was applied on the wall, also some textures are applied over one another and flicker in that same area. (Original room is hidden.)

![shot001](https://user-images.githubusercontent.com/48183219/153727194-4d5f5f45-69c0-4b5e-ba79-c68c0879748d.jpg)

**Comment by Lwmte** [comment]
Was it present before 1.4.6?

**Comment by Lwmte** [comment]
Also. Non-mqo is okay?

**Comment by Raildex** [comment]
@MatieTR Are the UVs correct in 0-1 space?

**Comment by MatieTR** [comment]
> Was it present before 1.4.6?

No, I downloaded 1.4.5 just to try and that works perfectly fine.

> Also. Non-mqo is okay?

Yes, .obj format works (although not very useable for me in Meta).

> @MatieTR Are the UVs correct in 0-1 space?

One texture was out of that range after exporting the room, although the issue was still present when I fixed UV coordinates. It wasn't out of range when I exported the room in 1.4.5.

Textures in mqo export are messed up in 1.4.6 and 1.4.7 even when exporting the room and importing it straight away, no modifications made in any external programs.

**Comment by MatieTR** [comment]
Sadly it still produces the same issue. I've also tried unticking a few other options in Settings i.e. aggressive texture packing, those didn't make any difference either.

**Comment by Lwmte** [comment]
Sadly I can't find the reason for that. Let's hope Monty et al finds reason. In the meantime, I recommend using .obj format.

**Comment by Lwmte** [comment]
Nevertheless.
a) Provide test level with a texture set which causes issues.
b) Tell the room number which geometry causes issues on export.

**Comment by Lwmte** [comment]
Also.
Rollbacked code up to 1.4.1. Your issue still happens there.

**Comment by Lwmte** [comment]
Fixed
