### ISSUE TITLE
Wadtool: vertex numbers are not preserved/matched when replacing a mesh

### ISSUE THREAD

**Issue by Kubsy** [MontyTRC89/Tomb-Editor#541]
Not sure if it's intended or it's done deliberately to do it manually but I replaced Lara's head mesh to include glasses. Unfortunately the vertex numbers weren't preserved and had to remap the hair and neck to match Lara_skin and Lara_scream. 

I think it would be good if they were preserved. I know it's not a huge deal but it would be good.

**Comment by Castigavi** [comment]
Frankly I don't think it's possible..? First thing assimp does some weird magic to vertices that in the past resulted in weird issues like missing or incorrectly connected vertices (lwmte fixed that). Moreover, modern 3d editing programs also shuffle vertex ids, so even if WADTool kept that your exported file would most likely had them shuffled again anyway.

**Comment by Kubsy** [comment]
Yeah what prompted me to write this issue was when I was adding glasses to Lara, her vertices were messed up and had to adjust for her neck and hair, thanks with Dejan's help. 

Well that kinda sucks that Blender shuffles them :/

**Comment by Stranger1992** [comment]
I see this has been closed. Has it been resolved? I had the exact same issue too.

**Comment by Castigavi** [comment]
> I see this has been closed. Has it been resolved? I had the exact same issue too.

I believe it was closed as a won't fix due to issues mentioned above. If you need particular ids for particular vertices just apply them manually using mesh editor.
