### ISSUE TITLE
Feature request: Be able to export the whole texture page from an object 

### ISSUE THREAD

**Issue by Kubsy** [MontyTRC89/Tomb-Editor#547]
following from #539 users should also be able to export whole texture page of an object as the texture split into smaller pieces doesn't help them and they have to switch to strpix to do that.

**Comment by Lwmte** [comment]
WT already has an option to export specific texinfos in a single page for a given mesh.
No functionality exists for exporting whole object along with specific texinfos, but whether it should be implemented, it will be a part of object export functionality.
