### ISSUE TITLE
Texinfos limit in WadTool?

### ISSUE THREAD

**Issue by WalrusTR** [MontyTRC89/Tomb-Editor#549]
In this wad I was trying to add a retextured key hole (1 texture, 24 texinfos) to a wad that already has 31784 texinfos. When I try to save the wad, I get this error message:
![unknown](https://user-images.githubusercontent.com/43911310/166231859-400e8bb0-422c-432a-b7c5-7ce83bd46e33.png)

If I remove the new key hole replacing it with the old one (9 texinfos), the wad is correctly saved.

**Comment by Lwmte** [comment]
Fixed
