### ISSUE TITLE
WT: Add ability to change padding value

### ISSUE THREAD

**Issue by Castigavi** [MontyTRC89/Tomb-Editor#553]
WADTool automatically adds padding (8px I believe) when you export an object with "pack textures" option applied. This is not an issue when you edit meshes only, but if you want to edit textures as well, padding can actually be an annoyance for few reasons, eg: 

- Automatic padding makes it hard to specify what are the actual texture boundaries and it makes it a bit harder to replace the texture before importing meshes back.
- Padding adds up to texture size, so if you use big textures you might end up with your object's textures taking up to several texture files (this is especially annoying with sphere horizons).

Because of that I propose to add an option to change padding in WADTool as well (in settings or maybe in the export window?). Tomb Editor has an option to modify that, so it would be logical for WADTool to have that too.

**Comment by Lwmte** [comment]
Is it ok if it will be an option in WT settings?

**Comment by Lwmte** [comment]
Added
