### ISSUE TITLE
TEN: Weapons: weapons don't appear in their original spot after converting wad to TEN

### ISSUE THREAD

**Issue by Kubsy** [MontyTRC89/Tomb-Editor#559]
Weapons appear slightly above the backpack after converting wad from TR4/TRNG to TEN. Might be a converter issue or wad I am not sure https://streamable.com/0vtz5k

**Comment by Lwmte** [comment]
Fixed

**Comment by Kubsy** [comment]
Not foxed :kryshidethepain:

**Comment by Lwmte** [comment]
Fixed on TE side.
