### ISSUE TITLE
TE: Importing .anim files with links to other animations higher than wad limit causes build failure

### ISSUE THREAD

**Issue by Gancian** [MontyTRC89/Tomb-Editor#560]
Sorry for the confusing title, let me explain: when you export an animation in WadTool, the .anim file also saves the number in the "next anim" slot and every state change set in it.
You can set any number inside these settings as long as it's an existing animation in YOUR wad.
However, if you export the .anim and import it in a different wad having LESS animations, the numbers stay the same, even though the actual animation linked does not exist. No warning is displayed.
The "problem" happens when you try to build and play your level and didn't notice this discrepancy. Inside the Tomb Editor this message pops up:
```
There was an error. Message: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
```
Without any further explanation.
It took me a couple of days to realise I missed to adjust a State Change after importing an animation from TrSearch.

**Comment by Lwmte** [comment]
Fixed
