### ISSUE TITLE
TE: The program crashes when trying to cancel compile

### ISSUE THREAD

**Issue by Jakub768** [MontyTRC89/Tomb-Editor#569]
Tomb Editor crashes when trying to cancel level compilation.

TE would hang at 98% then TE would stop responding, and have to: wait several minutes to regain control, or force quit on task manager,

For me, it was a rare occurrence so it is quite hard to reproduce.

**Comment by Lwmte** [comment]
I think it was fixed long ago by Raildex cancellation token PR.

**Comment by Nickelony** [comment]
> I think it was fixed long ago by Raildex cancellation token PR.

Yea, I also thought this was already fixed. I'm closing this issue then.
