### ISSUE TITLE
TIDE: can't drag any file after compiling the script

### ISSUE THREAD

**Issue by LoreRaider** [MontyTRC89/Tomb-Editor#581]
After I compile any TRNG script in TIDE, I can't drag any file I select on either the desktop or file explorer

I'm using Windows 11 and I'm on dotNET6 branch

Repro steps:
-Open TIDE and load a TRNG project
-Go to the script editor and click on "Build script"
-Let the script compile and then try to hold and drag any file from the desktop or file explorer

I haven't tested if it happens with TR4 vanilla or TR2/3

**Comment by Nickelony** [comment]
Foxed. :)
