### ISSUE TITLE
WadTool: can't batch import animations

### ISSUE THREAD

**Issue by LoreRaider** [MontyTRC89/Tomb-Editor#584]
I'm trying to batch import some animations in .anim format into LARA object, once imported it shows a message saying that all the animations are successfully imported but it doesn't import any.

Repro steps:
-download the provided package AnimsBatch.zip, open WadTool and load Lara.wad2.
-select LARA object and click "Edit animations".
-go to "Animations"->"Batch"->"Import" and choose "Naotheia_PoleSwing-5" folder.

WadTool will pop up a message that 22 animations were imported successfully, but looking at the animations list, there are none imported.

[AnimsBatch.zip](https://github.com/MontyTRC89/Tomb-Editor/files/9228665/AnimsBatch.zip)

**Comment by Lwmte** [comment]
Fixed
