### ISSUE TITLE
Wad Tool: Missing and mistaken slots.

### ISSUE THREAD

**Issue by Adngel** [MontyTRC89/Tomb-Editor#590]
Doing some enemies test, I've found that when copying objects from originals TR levels on to the TEN wad, many objects are taken to a mistaken slot, or they don't have slots. I'll try to put here the ones I've found till the moment.

### TR1
- [x] #604

### TR2
- [ ] **SHOTGUN GOON** (Opera.wad): It hasn't got slot.
- [x] **RAT** (Opera.wad): It is copied over BIG_RAT instead of RAT
- [ ] **STICK-WIELDING_GOON** (Opera) Is copied over MP_WITH_STICK althogh their animations are different.
- [ ] **YELLOW MORAY EEL** (Wreck.wad): It hasn't got slot.
- [x] **Pointer (nullMesh)?** (Islands.wad): Is copied over CIVVIE Instead of Knifethrower_Knives
- [x] ~~**MAFIA** (TEN) No enemy was copied over this slot~~ Mafia are the TR5 submarine enemies.
- [x] ~~**MAFIA2** (TEN) No enemy was copied over this slot~~
- [x] ~~**MESHSWAP_MAFIA2** (TEN) I don't know what this object is~~

### TR3
- [x] #603
- [x] #614
- [x] #611
- [x] **MERCENARY** (Crash.wad): It is copied over HAIR instead of TROOPS
- [x] #610
- [x] #609
- [x] #608
- [x] #607
- [x] #606

### TR4
- [x] #612
- [x] #613
- [x] **REVOLVER** is not being copied in the slot (980) when taken from another TR4 level. (Reported by Die Basis).

**Comment by Stranger1992** [comment]
Will amend all the incorrect entries.

**Comment by Adngel** [comment]
Closing old issue, new one will be created if required.
