### ISSUE TITLE
WT: state changes low frame clamp happens when typing

### ISSUE THREAD

**Issue by Joey79100** [MontyTRC89/Tomb-Editor#593]
When you edit a **State change**, and you type a **Low Frame** that is higher than **High frame**, then WT automatically clamps it so it doesn't go above the High frame.
This is done to prevent incoherent state changes.

The idea is good, however the implementation makes it a bit annoying: it was thought for editing _existing_ State changes.

However, if you're writing a _new_ State change, you usually write from left to right:
- State ID
- Low frame
- High frame
- Next anim
- Next frame

But when you type into the **Low frame** field, **High frame** is still 0.
So what happens is no matter what you type in Low Frame, it is reset to 0 as you switch to the next field.

So you have to type High frame first, then switch back to Low frame, and there it will not reset to 0.

**Comment by Lwmte** [comment]
What do you propose to do to fix this?

**Comment by Joey79100** [comment]
Could the clamping happen when the line loses focus / not as long as the focus is still in one of the fields of the line?

**Comment by Lwmte** [comment]
I don't think so, it would be too hacky to do that. As alternative, I may just suggest not to clamp when high frame field is 0.

**Comment by Lwmte** [comment]
Fixed (it won't clamp when high frame is 0 now)
