### ISSUE TITLE
WT: State changes: Animation name in tooltip is catalog name, not WAD name

### ISSUE THREAD

**Issue by Joey79100** [MontyTRC89/Tomb-Editor#599]
Very minor thing:

In the State changes window, you can hover the **Next animation** column, and it will show the name of the animation.
But this name is the name stored in **TRCatalog.xml**. It should be showing the name of the actual animation in the WAD.

--------------------------------------------

For example:
Lara's animation 101 is named "**JUMP_FORWARD_START_TO_REACH_ALTERNATE_UNUSED**" in **TrCatalog.xml** :
```xml
<anim item="0" id="101" name="JUMP_FORWARD_START_TO_REACH_ALTERNATE_UNUSED" 
```

Since it is unused, I reused it for another purpose, and named it accordingly: "**RUN_START_END_TO_STAND**".

This animation is referenced in my animation **6** (**RUN_START**) via a State Change.
But when I select animation **6** (**RUN_START**), open the State Change window, and hover the line which references my animation, it shows the old name that is in **TrCatalog.xml** instead ("**JUMP_FORWARD_START_TO_REACH_ALTERNATE_UNUSED**"):

![image](https://user-images.githubusercontent.com/12445716/186680491-35c5d9a7-32b7-471b-ac1d-e2172a037035.png)

_Also don't mind my idiotic state changes with an animation that is probably never gonna be triggered, I literally just noticed this 🌚 And this is what made me notice this bug._

**Comment by Lwmte** [comment]
Fixed on #597 PR (sorry, accidentally pushed to that branch).
