### ISSUE TITLE
TE: Node Editor missing functions

### ISSUE THREAD

**Issue by Joey79100** [MontyTRC89/Tomb-Editor#601]
These are functions I think are the most commonly used by builders, and would benefit being added to the existing list of node functions ([Tomb-Editor/TombLib/TombLib/Catalogs/TEN Node Scripting/**Default.lua**](https://github.com/MontyTRC89/Tomb-Editor/blob/node_editor/TombLib/TombLib/Catalogs/TEN%20Node%20Scripting/Default.lua))

# ACTIONS

## Objects
- [x] Enable object (`object`)
- [x] Disable object (`object`)
- [x] Set object animation (`object`, `animationId`)
- [x] Set object state (`object`, `stateId`)
- [ ] Set object as target (`object`)

## Rooms
- [x] Flipmap (`roomId`, `mode`) -- *mode being: "flip", "on", "off"*

## Misc
- [x] Display text (`text`, `position`) -- *no idea how to encode position*
- [x] Play audio track (`trackName`, `mode`) -- *mode being loop or single shot*
- [x] Add item to inventory (`itemId`, `count`)
- [x] Remove item from inventory (`itemId`, `count`)

# CONDITIONS

## Objects
- [x] If object name is (`object`, `name`)
- [x] If object's animation is (`object`, `animationId`)
- [x] If object's current state is (`object`, `stateId`)

## Rooms
- [x] If room's flipped state is (`roomId`, `state`) -- *state being: "on", "off"*

## Misc
- [x] If key is pressed (`key`)
- [x] If key is held (`key`)
- [x] If item is in inventory (`itemId`, `operator`, `count`)
-

**Comment by Kubsy** [comment]
all of these are implemented.
