### ISSUE TITLE
TE: Node functions: handle Step parameter for numerical fields

### ISSUE THREAD

**Issue by Joey79100** [MontyTRC89/Tomb-Editor#602]
When making a function that has a Numerical argument, you can specify Min and Max, but not Step.

Specifying steps would prevent scenarios like this one:
![image](https://user-images.githubusercontent.com/12445716/188318618-416e247b-a416-4f6b-9d96-36b852a035b9.png)

As numerical fields only accept 2 ENUMDESC parameters, step could be the 3rd one.
For example:
```[ 0 | 1000 | 1 ]```
This would allow any integer number between 0 and 1000.

_(hope I didn't just miss an already existing feature)_

**Comment by Lwmte** [comment]
Implemented
