### ISSUE TITLE
WT: UV Mapping

### ISSUE THREAD

**Issue by illyaine** [MontyTRC89/Tomb-Editor#621]
It would be nice if you could also apply UV mapping textures directly to an object in the WADTool without having to go through external programs.
Of course there are level builders who know the programs and are familiar with them. But on the other hand, there are those who can't do this, or level builders who have to start all over again and get used to it.

Therefore, such a small UV mapping editor, where you could apply the textures to an object, would be a great thing. Then one would possibly also take away the fear of many, so that these objects would be made available to others.

**Comment by Nickelony** [comment]
I'm afraid this feature is too much for a tool like WadTool. It is not a 3D modeling software like blender, 3DS or Maya. Creating a complete workflow for UV unwrapping (with seam marking of course) would require an astronomical amount of work for something that wouldn't really benefit anyone, as most people, who know how to UV unwrap, most likely know how to do so in other programs.
WadTool currently allows you to re-texture each individual face of an object, and I'm afraid that's as far as we can push it.
