### ISSUE TITLE
Divide floor/ceiling square

### ISSUE THREAD

**Issue by illyaine** [MontyTRC89/Tomb-Editor#622]
![8783BED3-9DBA-45A0-A4BE-B8DB93C8052A](https://user-images.githubusercontent.com/915558/196019817-a14345ca-6922-412b-baee-0df6b9734987.jpeg)

If you can subdivide the floor/ceiling square again, then you could build something "smoother" architecture in the level.

**Comment by Lwmte** [comment]
Duplicate of #731
