### ISSUE TITLE
Diagonal wall with ceiling division on edge of portals creates a rogue triangular block on one side

### ISSUE THREAD

**Issue by GeckoKid-JW** [MontyTRC89/Tomb-Editor#627]
As shown in the screenshot, when using subdivided diagonal ceiling tiles on the edge of a room there'll be a rogue triangle attached to the bottom part of the ceiling from the top.

![image](https://user-images.githubusercontent.com/111427436/199489230-57daa275-22ee-45b7-af52-7ee91c6a18e0.png)
So it seems that it only happens when the edge is facing South.

**Comment by GeckoKid-JW** [comment]
[diagonalTest.zip](https://github.com/MontyTRC89/Tomb-Editor/files/9920316/diagonalTest.zip)
test file attached here.

**Comment by Nickelony** [comment]
Fixed, OMG how was this never found?
