### ISSUE TITLE
TE: Default textures when rooms created newly

### ISSUE THREAD

**Issue by goldlife2904** [MontyTRC89/Tomb-Editor#639]
Is it possible that default textures (when u just create a room and texture NOTHING) are automatically textured while creating a room?
Like (example) green for the floor and light gray for the wall - or  (which is indeed better)  depending on the settings in the editor 😅 - that would be even better if you could define it yourself. Of course I can also texture by myself when I created a room. But it would be even more convenient if the TE could do this directly from the house. Like as a default, "Preview Textures" applied automatically when creating a room.

![1](https://user-images.githubusercontent.com/75839472/206717991-4fe4e50e-d01e-48d6-83e1-421eb4a79fee.jpg)

**Comment by Nickelony** [comment]
This feature has been officially added in 1.7.1.
