### ISSUE TITLE
WT: "quick interpolate" feature

### ISSUE THREAD

**Issue by Joey79100** [MontyTRC89/Tomb-Editor#648]
When animating, interpolating between 2 frames is something you do pretty often.

But many times, you already have the correct animation length, and you just edited 1 pose in the middle, and you want to interpolate this frame with another one without changing the number of frames in between.

Having a quick way to interpolate a selection of frames without having to type in a number would be quite a big time saver.

-------------

I'm not exactly sure of how this should be implemented. Ideally, there should be a keyboard shortcut.
- One idea could be to **Ctrl + Alt + click and drag** over a selection of frames (it will automatically interpolate all the frames in between the first and last in the selection).
- Another idea would be to hold Ctrl while clicking the Interpolate button in the toolbar (if it gets added - see #647 for this)

**Comment by Lwmte** [comment]
I have added a shortcut (Ctrl+I), and also made default value of interpolation dialog a length of current selection. Please check if it's now more convenient.

**Comment by Joey79100** [comment]
Forgot to close this after discussing it on Discord (I think?). Thanks!
