### ISSUE TITLE
TIDE: add an "Exit" command in the File menu

### ISSUE THREAD

**Issue by Joey79100** [MontyTRC89/Tomb-Editor#654]
This is _extremely_ minor feature request.

In (almost?) all programs that feature a "File" menu, this menu includes an "Exit" command.

Usually the exact same behavior is achieved by clicking the X to close the window.
But in some programs it just closes the active window, whereas the "Exit" command actually closes the entire instance of the program (including all the windows it spawned). An example of that is Visual Studio Code.

So my brain has taken the habit of closing programs this way when they have a File menu. But it becomes very very very very slightly frustrated with TIDE, because its File menu is missing an Exit command:

![image](https://user-images.githubusercontent.com/12445716/209836677-67493ad8-fb08-4706-9ce5-7ad2f162e5c9.png)

Would be nice if it could be added, at least for consistency with other programs in the suite (Tomb Editor, WadTool and SoundTool all have it, although each time with a different icon and/or text).

**Comment by Nickelony** [comment]
Done.
