### ISSUE TITLE
TIDE: Exception when attempting to launch TE from level list, if TE has some compatibility options set

### ISSUE THREAD

**Issue by Lwmte** [MontyTRC89/Tomb-Editor#658]
![Clipboard-1](https://user-images.githubusercontent.com/3331699/210068162-c3454526-905d-47e2-b3ce-2cb0771e7d32.png)

This exception happens if you try to double-click in TIDE level list to launch a TE. It occurs if TE itself has specific compatibility options set, such as "Run as administrator".

**Comment by Nickelony** [comment]
Seems to be 🦊
