### ISSUE TITLE
NET6 issues

### ISSUE THREAD

**Issue by Lwmte** [MontyTRC89/Tomb-Editor#667]
Here is the list of issues that started to appear after TE was ported to NET6. None of these issues were present with old .NET Framework version.

- [x] Designer is throwing an exception when trying to enter complex forms, such as Level Settings.
- [x] Button sizes in DDGV controls may randomly change, although usually this goes away after clean & rebuild.
- [ ] Icons are dereferenced from resources and appear as "embedded" to a control.
- [ ] Some nested and docked controls (such as path panels in first page of Level Settings) are incorrectly rearranged or shuffled when showing / hiding them in runtime. Currently solved that by a hack which sets panel height to 0 instead of hiding it.

**Comment by Nickelony** [comment]
Fixed exception.
For future:
1. Close VS
2. Open `~CLEAN-SOLUTION.bat`
3. Rebuild entire solution
4. Done.
