### ISSUE TITLE
Crash when selecting mesh edit on Bridge Flat (WadTool TR2)

### ISSUE THREAD

**Issue by mizunosuisei** [MontyTRC89/Tomb-Editor#694]
WadTool crash when selecting mesh edit on TR2 Bridge Flat object. V1.6.6.

![Capture](https://user-images.githubusercontent.com/113810735/235355449-8362f42f-17e0-4f36-98a9-5990b768af34.PNG)

**Comment by Lwmte** [comment]
Fixed in 6bbbd0b3b76f41da29321c47cb64e4d292e3cca7
