### ISSUE TITLE
TE: Index out of range error

### ISSUE THREAD

**Issue by Kubsy** [MontyTRC89/Tomb-Editor#696]
Zuxuna had this following problem:

![image](https://github.com/MontyTRC89/Tomb-Editor/assets/80340234/5780930d-aa1f-437e-ba3e-f9d284d9277d)

[message.txt](https://github.com/MontyTRC89/Tomb-Editor/files/11471437/message.txt)

Wad:
https://drive.google.com/file/d/1zKfGy3k5aDxFScBD9JPnTt4Mvb5z19RB/view?usp=sharing

**Comment by Lwmte** [comment]
Fixed in f52e270f354e4c3272627f5359a9a496df1d4a03
