### ISSUE TITLE
TombEditor: Multi copy+pasting moveables/statics will give the same lua name 

### ISSUE THREAD

**Issue by Kubsy** [MontyTRC89/Tomb-Editor#698]
If you multi copy-paste a static with lua name: "Animating_247" and paste 4 of them then all 4 have "Animating_247" as their lua name.

I copy + pasted this moveable 4 times
![image](https://github.com/MontyTRC89/Tomb-Editor/assets/80340234/afe16b7f-ad0b-4fe3-ad26-95b14ba3f646)

all 4 now have the same lua name:
![image](https://github.com/MontyTRC89/Tomb-Editor/assets/80340234/43a2da89-5881-44c7-abdb-a4b6be32013a)
![image](https://github.com/MontyTRC89/Tomb-Editor/assets/80340234/5ecc33e5-8372-4999-9cca-6f26e3fb6ac0)

**Comment by Lwmte** [comment]
Fixed
