### ISSUE TITLE
WT: copying a non-TR4 object into a TEN WAD does not remap sounds anymore

### ISSUE THREAD

**Issue by Joey79100** [MontyTRC89/Tomb-Editor#705]
1. In the source panel (right side), open a TR1-3 or TR5 original level.
    For example, TR1's Lost Valley.
2. In the destination panel (left side), create a new TombEngine WAD.
3. In the source panel, double-click on an object to copy it into the TombEngine WAD.
    For example, the Tyrannosaur.
4. Open the object in the animation editor, and find an animation that has a recognizable sound.
    In case of the TYRANNOSAUR, Animation 5 has the roar sound.
5. Open the Anim commands window and find the sound. The sound should be correct.

_In case of the T-Rex, the TR1 sound is 71: T-REX_ROAR._
_In the TEN WAD, it should be remapped to sound 394: TR1_T-REX_ROAR._

In 1.6.6, it is correctly remapped to sound 394.
In 1.6.7, the sound remains ID 71, which is TR4_GENERIC_SWOOSH in TEN.

**Comment by Lwmte** [comment]
I think it was fixed recently, and it is the same issue which was reported by LGG, so I am closing this.

**Comment by Joey79100** [comment]
Just tested, can confirm it is fixed!
