### ISSUE TITLE
Trigger Triggerer always active

### ISSUE THREAD

**Issue by illyaine** [MontyTRC89/Tomb-Editor#708]
Trigger Triggerer currently not functional

Trigger Triggerer Nullmesh object placed on a square. In the TE Select options the option "Set trigger triggerer/minecarf left (TR3) is activated.

In the game, the trigger triggerer is activated immediately.
Antitriggering doesn't do anything either. This means that the "Trigger Triggerer" function cannot currently be used.

Edit: Sorry if it's a TEN issue. This is difficult to classify here.

![Screenshot 2023-07-11 190632](https://github.com/MontyTRC89/Tomb-Editor/assets/915558/84066bd8-13c6-4d76-864e-0c962fca49a1)

**Comment by Kubsy** [comment]
trigger triggerer doesn't work as far as I know, however this can be very easily replicated with enabling/disabling volumes

**Comment by illyaine** [comment]
Yes thank you. Jörg had already mentioned that. Hadn't thought of this at all. :)

**Comment by Lwmte** [comment]
Wrong repo. If you still need this to be fixed, please move to TEN issues.
