### ISSUE TITLE
TE: reorder eventsets, or sort them by name (QOL)

### ISSUE THREAD

**Issue by Joey79100** [MontyTRC89/Tomb-Editor#713]
**Very minor** stuff here. Look at the left column:
![image](https://github.com/MontyTRC89/Tomb-Editor/assets/12445716/3e3d2b7e-3ed4-49a1-a1fd-559d05ed1508)

The order of the eventsets here, reflects the order in which they were added to the project.
This order is remembered and will not change, neither automatically nor upon trying to drag the elements.

_And I am a little annoyed by the lack of order in this list (even though I seemingly am not annoyed by the lack of order on my desk... I mean the real life one)._

To make it easier to find a specific eventset when the list is long, TE should either:
- Ideally, have "up" and "down" buttons to reorder the eventsets ;
- Or simply always sort them by name. Maybe this can be done upon re-opening the window, so it doesn't move every time you rename an eventset?

**Comment by davidmarr** [comment]
Now that we can call up eventsets, the list of eventsets may increase. There is a need for this functionality

**Comment by Lwmte** [comment]
Added in #733
