### ISSUE TITLE
TE: add a node to activate cameras in level

### ISSUE THREAD

**Issue by Gancian** [MontyTRC89/Tomb-Editor#714]
The Node Editor needs a node to activate a camera. It's one of the basic triggers in the original Level Editor, and will definitely make new builders more accustomed to the new Node Editor and Volume Triggers

**Comment by Stranger1992** [comment]
Hi Gancian,

This node has already been made and will be in the next update :)

**Comment by Stranger1992** [comment]
![image](https://github.com/user-attachments/assets/c4f06deb-2e81-4751-b92e-3ee36eaebd79)
