### ISSUE TITLE
Tomb Editor Crashes if Assign sound button is pressed without selecting a sound

### ISSUE THREAD

**Issue by TrainWrack** [MontyTRC89/Tomb-Editor#722]
![image](https://github.com/MontyTRC89/Tomb-Editor/assets/120750885/78fb221d-fdb1-4beb-892c-54b25ee75039)
![image](https://github.com/MontyTRC89/Tomb-Editor/assets/120750885/ab46212b-3d96-4fea-a521-1498a5de1ac9)

If you press continue you are unable to assign sounds and have to restart the editor.

**Comment by Lwmte** [comment]
Thanks, fixed!
