### ISSUE TITLE
Enhancement: Water Room strength 0 should not show any movement in the water room.

### ISSUE THREAD

**Issue by TrainWrack** [MontyTRC89/Tomb-Editor#735]
Water rooms move even when the room effect is set to none with strength set to 0. Would it be possible to have a static water room without the wobble effect?

![image](https://github.com/MontyTRC89/Tomb-Editor/assets/120750885/408944f3-162a-41a5-b53a-c3c2725a7708)

https://www.youtube.com/watch?v=xoztI10lB1g&feature=youtu.be

**Comment by Lwmte** [comment]
TEN issue. Please move to TEN repo.
