### ISSUE TITLE
Discomfort in displaying TE coordinates in the new way

### ISSUE THREAD

**Issue by AkyV** [MontyTRC89/Tomb-Editor#736]
I saw you removed displaying local (room) coordinate values for TE 1.6.9., so we can see only global (level) coordinates everywhere, in tooltips and such.

Except - these are still all local:
- portal tooltip coordinates,
- main tooltip (upper left corner) - or whatever you call it - for portals, light effects,
- search function coordinates for portals, light effects, and texture tiles,
- "Objects in Room" window for light effects.
- EDIT2: Sector Pos in object tooltips. EDIT4: and in Action trigger parameter values.
- EDIT3: "Triggered in..." in object tooltips.

(EDIT: The direction of the development is good, my suggestion is a full-global system.)

Plus:
Showing coordinates at object tooltips in the new way - vertical coordinates are inverted (just like at the older editors), i.e. the ones above Level 0 are negative. - Remaining local coordinates still show positive values for light effects in this realm, which is a contradiction.

I find all of these a bit disturbing.

**Comment by Lwmte** [comment]
Sector position is correct. For light objects, tooltip is fixed.
