### ISSUE TITLE
TIDE: Broken functions

### ISSUE THREAD

**Issue by AkyV** [MontyTRC89/Tomb-Editor#738]
- TRNG script autocomplete started working badly for me. (Probably a new issue.)
This means only one successful try - then I need to close and restart the project for another only one successful try. Then again and again...
For other tries, the autocomplete window won't pop up while writing.

TIDE shortcut keys fail for the side bar button functions (definitely older issues, I just haven't told so far, because they are micro):
- F3 for project directory and
- F4 for game start.

**Comment by Nickelony** [comment]
This is the first time I've ever seen a bug not happen when running through Visual Studio, but when opening the app while VS is closed, it's bugged... WTF!
