### ISSUE TITLE
WT: False sound displayed

### ISSUE THREAD

**Issue by AkyV** [MontyTRC89/Tomb-Editor#756]
(Game version: TR4)
Animation editor:

Eventually all the existing animations (so every random animation I just examine, of Lara or else) in every WAD/WAD2 I try, has a fake 0 LARA_FEET sound, at a random (?) frame of the animation, in Anim Commands Editor. - Thankfully they seem not being played in the game.

**Comment by Lwmte** [comment]
I can't reproduce this issue. Please provide faulty wad/wad2.

**Comment by AkyV** [comment]
Hello!
Your request is very easy, because it happens to me actually with ANY WAD/WAD2. :) - So even with the initial ones.
That is why I attach now the WAD that probably is the "most initial" to the builders: the original tut1.wad, provided for winroomedit.exe, saved at 05.11.2000. - It also happens to me in this WAD.
Plus, I also attach three random screenshot of this WAD in WT, seeing those false sounds in Anim Commands Editor.

![image](https://github.com/MontyTRC89/Tomb-Editor/assets/34724172/22217b54-b0fe-4dfb-9e48-7e5916c3e176)

![image](https://github.com/MontyTRC89/Tomb-Editor/assets/34724172/06c21cdc-b913-476a-9d8b-fd4db3ee7148)

![image](https://github.com/MontyTRC89/Tomb-Editor/assets/34724172/55345501-bfea-4053-b39a-251cdea4f337)

[tut1.zip](https://github.com/MontyTRC89/Tomb-Editor/files/13864749/tut1.zip)

**Comment by AkyV** [comment]
It seems it only happens when I right-click on the frame stripe, to open anim command menu.
I mean, it won't happen with anim command button on the left.

**Comment by Lwmte** [comment]
It's not a false sound displayed. It is default animcommand which is created when you click "Create anim command..." menu entry.
