### ISSUE TITLE
TE: Importing .prj files subtracts 4 from room lighting values

### ISSUE THREAD

**Issue by NateH96** [MontyTRC89/Tomb-Editor#759]
As the title says. Placed lights remain intact but room lighting subtracts 4 from each RGB value. E.g.: a room with a lighting value of 24,24,24 in NGLE becomes 20,20,20 in TE.

**Comment by Lwmte** [comment]
It's not a bug but intentional light intensity adjustment, because TE internally uses floating-point values for keeping colors, not byte RGB values.
