### ISSUE TITLE
TIDE: character swap when updating a plugin

### ISSUE THREAD

**Issue by LoreRaider** [MontyTRC89/Tomb-Editor#760]
As the title says, special characters tend to be swapped inside english.txt file when adding or updating a plugin

Repro steps:
-Create or open a project made with TRNG engine
-Open english.txt and type a special character (for instance '€') in one of the string slots
-Add or update a plugin in plugins section

**Comment by Nickelony** [comment]
I can't replicate it. Does it still happen in 1.7?

**Comment by Nickelony** [comment]
Seems to be 🦊
