### ISSUE TITLE
TE: Cleanup autosaves won't work

### ISSUE THREAD

**Issue by AkyV** [MontyTRC89/Tomb-Editor#764]
As the title says, it won't work any more - I have just realized it. My level folders were full of autosaves, since about summer (even before the file name got the "backup" label), some folders had almost 1000 backup files. I needed to delete them manually. (I have the default autosave settings, though.)

**Comment by Nickelony** [comment]
It might have something to do with either the file name pattern being changed, so it's easier to detect by TIDE, or this might've been a thing since the .NET 6 port.

**Comment by Nickelony** [comment]
🦊
