### ISSUE TITLE
Moving objects with gizmo just became more sluggish

### ISSUE THREAD

**Issue by Nickelony** [MontyTRC89/Tomb-Editor#802]
Apparently moving objects with gizmo just became slower. Someone needs to do some proper testing on this before we can call this an actual issue.

**Comment by Raildex** [comment]
"more sluggish" is of no help.

**Comment by Nickelony** [comment]
> "more sluggish" is of no help.

Means it became laggier / slower

**Comment by Raildex** [comment]
compared to what? there is no profiling data, no comparison video or anything

**Comment by Nickelony** [comment]
> compared to what? there is no profiling data, no comparison video or anything

That's why this needs investigating. We need to check whether there have been any changes made to that code.
This has been reported by someone on the Discord server. I haven't verified if this happens on my end as well. We need to compare 1.7 to 1.7.1.
