### ISSUE TITLE
TEN sound overrides: few errors (assets/catalogs)

### ISSUE THREAD

**Issue by Joey79100** [MontyTRC89/Tomb-Editor#808]
[ Not sure where to put this - this is about TombEngine, but this is related to the catalogs you can find on its website and not TombEngine itself, but there are catalogs that are distributed through Tomb Editor - so here it is]

# TR1
- [x] In `TR1_Override.xml`, samples are missing for the following sounds:
  - TR1_LARA_BODYSLAM (samples exist but their names is wrong).
  - TR1_LARA_USE_OBJECT
- [x] In `TR1_Override.xml`, multiple sounds have been given a **Pitch**, they should all be **Pitch 0**.

- Overall, I'm not sure about the volume, but I haven't checked the original game.
  **TR1_LARA_BODYSLAM** noise in particular sounds too loud (Volume 100, but other sounds are too), or maybe it's **TR1_LARA_JUMP** that is not loud enough in comparison (Volume 30, probably inherited from TR4).

# TR2
- [x] In `TR2_Override.xml`, samples are missing for the following sounds:
- [x] LARA_WET_FEET
- [x] TR2_LARA_USE_OBJECT
- [x] TR2_LARA_MAGNUMS_FIRE
- [x]  LARA_PICKUP
- [x] TR2_UI_CONTROLS
- [x] TR2_UI_MEDI
- [x] TR2_LARA_USE_OBJECT
- [x] In `TR2_Override.xml`, override for `TR4_Lara_Climb_Walls_Noise` is missing
- [x] In `TR2_Override.xml`, override for `TR5_Generic_Sqks_Low` is missing (the valve sound)

# TR3
- [x] Sample `TR3_LARA_GRABBODY_01.wav` has been named `TR3_LARA_GRABBODY_.wav` (missing the **01**).
- [x] In `TR3_Override.xml`, sound `TR3_BLOCK_SOUND` has been given Mode **One shot rewound**, it should be **One shot wait** or **Loop**

# TR4
- [x] In `TEN_ALL_SOUNDS.xml`, sound `TR4_Lara_Jump`  has been given **Volume 30**, it should be **Volume 65**.

# TR5
- [x] In `TR5_Override.xml`, sound `TR5_LARA_GRABBODY` has been given **Id 54**, it should be **Id 55**.
- [ ] In `TR5_Override.xml`, sound `TR5_LARA_SWIM` has been given **Pitch -15**, it should be **Pitch -35**.
- [x] In `TR5_Override.xml`, override for `TR4_Pushable_Block` is missing (TR5 reuses the TR4 sound but with Pitch -20)

**Comment by Stranger1992** [comment]
Super super helpful, thank you so much.

The only point I have not changed is:

` In TR5_Override.xml, sound TR5_LARA_SWIM has been given Pitch -15, it should be Pitch -35.` 

As that is incorrect. The sound in tr5 is higher.
