### ISSUE TITLE
TE: Massive performance difference between 1.6.9 and 1.7 when working with very large rooms

### ISSUE THREAD

**Issue by Nickelony** [MontyTRC89/Tomb-Editor#817]
When modifying geometry in very large rooms (larger than 100x100), TE's performance has gone from acceptable to completely unusable.

So far, it is confirmed that the 1.7.1 update is not the cause of this. It might have something to do with the rewrite of `RoomGeometry.cs` I've done.

I have also confirmed that using a fixed array for textures in `Block.cs` doesn't help the problem.

**Comment by Raildex** [comment]
Do you have a project for testing?

**Comment by Nickelony** [comment]
> Do you have a project for testing?

This ended up being the Enum parsing being at fault, it's all fixed now. I just forgot to close this issue.
RoomGeometry ctor execution time went from 280-300ms to 70-100ms.
