### ISSUE TITLE
seeing error - center_settings.bin access denied

### ISSUE THREAD

**Issue by LoneckCZ** [MontyTRC89/Tomb-Editor#828]
After installation when I launch TombIDE I see error "Access to the path C:\Program Files\Tomb Editor\TIDE\NGC\center_settings.bin is denied".
![error](https://github.com/MontyTRC89/Tomb-Editor/assets/83338397/ccea782a-64e7-410d-94b3-bcb60c2f4696)
Anybody knows what's up with that?

**Comment by Raildex** [comment]
C:\ Program Files needs higher privileges.
Run TIDE as admin

**Comment by LoneckCZ** [comment]
> C:\ Program Files needs higher privileges. Run TIDE as admin

Yes, launching it as admin works. Thanks.
