### ISSUE TITLE
TE: Performance problems with detailed levels

### ISSUE THREAD

**Issue by illyaine** [MontyTRC89/Tomb-Editor#861]
I am currently building a level in TE with the TEN Engine, which contains many objects. 
Some time ago, when I displayed all the rooms, it stalled or jerked.
Now it also stutters when only ‘Draw Portals’ are displayed, and the textures are also displayed incorrectly.

I hope you can optimise the whole thing here so that I can work better again.
Unfortunately, it's a bit impractical when you can't display the rooms so well.

Hardware:
Prozessor:	AMD Ryzen 7 5800X 8-Core Processor 
RAM: 32,0 GB
GPU: AMD Radeon RX 6800 XT, Driver 24.7.1
Windows 11 Pro 64 Bit 23H2 Version

https://www.youtube.com/watch?v=X0SHQ6VtOhc

**Comment by Jakub768** [comment]
this has been fixed by @Raildex and will be included in the next update :)

**Comment by illyaine** [comment]
Thank you for the information. I'll wait for the update and get back to you if there are still problems :)
