### ISSUE TITLE
TEN - Shockwave issue

### ISSUE THREAD

**Issue by AkyV** [MontyTRC89/Tomb-Editor#862]
Whatever "inner radius" value I adjust in the node panel at the shockwave effect, I can't see any differences.
Either the inner radius is just a bit smaller than the outer one, or if it is really tiny.

**Comment by Stranger1992** [comment]
Hi AkyV. I believe I have fixed this with this commit : https://github.com/MontyTRC89/Tomb-Editor/commit/e605e458f9e12423faa8e7bdc39352b932708e0e
