### ISSUE TITLE
WT Feature request - Assigning foot sounds to an object

### ISSUE THREAD

**Issue by illyaine** [MontyTRC89/Tomb-Editor#866]
I would like to be able to assign a sample to an object, even faces. 
An example would be a carpet. Here you could assign the sound directly to the object so that the sound of the texture is not used in the actual room.

Currently, you have to enlarge a carpet according to the squares and assign a blanco texture with a matching sound, but with my idea, you would of course be more flexible with a large number of objects to which Lara can go.

**Comment by Nickelony** [comment]
This is less of an editor feature and more of an engine feature. You should try and post this in the Tomb Engine repo instead.
Unless an engine supports this feature, we can't really implement it in the editor. :(

**Comment by illyaine** [comment]
Thanks for your answer. I have created it directly :)

**Comment by Nickelony** [comment]
Since there's currently no engine supporting this, I'm closing this issue for now, but we can re-open it once there is an engine which has such functionality.
