### ISSUE TITLE
[Master Branch] All objects turn transparent from level if new WAD is added (TE and WT)

### ISSUE THREAD

**Issue by Stranger1992** [MontyTRC89/Tomb-Editor#871]
Hi.

On the current `master` branch (dated 6th August 2024), a bug happens when a new WAD is added.

Repro steps:

Tomb Editor:

1) Open any level
2) Add a new WAD to your level
3) All objects will disappear and will appear transparent
4) Objects will re-appear when the project is reloaded.

![image](https://github.com/user-attachments/assets/4badff86-3784-425e-8a5f-c97bbd273ac8)

WadTool:

1) Open any WAD into the destination side
2) Open any WAD into the source side
3) The object will appear transparent in the preview.

![image](https://github.com/user-attachments/assets/2c695940-6e9b-495a-8361-afd1c1b81020)

**Comment by Nickelony** [comment]
@Raildex Could this have something to do with the most recent changes to how textures are handled for wad objects?

**Comment by Raildex** [comment]
I will investigate
