### ISSUE TITLE
TE: Unofficial build from TE - object textures washed out

### ISSUE THREAD

**Issue by illyaine** [MontyTRC89/Tomb-Editor#876]
I had recently created an issue because of the performance.
https://github.com/MontyTRC89/Tomb-Editor/issues/861

Due to my detailed level of the many objects, it was no longer possible to build properly over time.
TokyoUS had therefore created a current build of the TE and the performance problem was gone, but the object textures are displayed blurred. TokyoUS told me to create an issue for this.

![CM4](https://github.com/user-attachments/assets/de417f97-4841-4b5f-ba8b-aea828b11a99)
![CM5](https://github.com/user-attachments/assets/4fff9959-933e-4af7-86db-86b20da4a125)

Edit: Nickelony just said on Discord that this is intentional. Due to the performance problems :)

**Comment by Stranger1992** [comment]
Hi @illyaine : Yes this is intentional. Internally: the texture size displayed is squashed down to a minimum but does not affect the final output. Thank you for reporting this but I will mark this as done.
