### ISSUE TITLE
Fill Tool not working correctly with the invisibility button on. [Tomb Editor]

### ISSUE THREAD

**Issue by Stranger1992** [MontyTRC89/Tomb-Editor#880]
If you use the fill tool (paint bucket) whilst in textured mode and also select the invisibility button (symbol with line through an eye) : the room geometry will not fill completely:

![image](https://github.com/user-attachments/assets/baee91e7-d0c3-43f7-b80d-d27154df8250)

![image](https://github.com/user-attachments/assets/0827a590-2950-41f2-a4a7-c415d0308411)

If you then press CTRL+Z / Undo: it will be filled as expected. However this is a bug and a regression.

**Comment by Nickelony** [comment]
🦊
