### ISSUE TITLE
TE: allow Ghostblock triangle flip on ceiling

### ISSUE THREAD

**Issue by LoreRaider** [MontyTRC89/Tomb-Editor#883]
When using ghostblocks (just like normal geometry) it's possible to flip the triangle by hovering the sector and pressing Alt+Click.
However, the same can't be done with the ceiling.

Repro steps:
- Add a ghostblock on a sector
- Raise or lower one of the 4 vertices of the ghostblock
- Press Alt+Click on the ceiling part of the ghostblock, nothing happens

Expected result: correct flip of the ceiling triangle

As you can see the imported geo rooftop has a different triangle flip than the ghostblock
![image](https://github.com/user-attachments/assets/37310c5c-7b7a-472b-9cfc-754aef2ba413)

**Comment by Nickelony** [comment]
This is already possible. You have to ALT+Click on the ceiling tile, rather than the ghost block itself. It's the exact same for floor tiles.
