### ISSUE TITLE
TE: erased textures on rooms rotation

### ISSUE THREAD

**Issue by LoreRaider** [MontyTRC89/Tomb-Editor#893]
When rotating a room, some textures gets erased from the extra walls segments of a floor or ceiling, so anything below E-D line and anything above R-F line

Repro steps: 
- Raise/lower a floor/ceiling and add wall segments
- Texture the segments
- Rotate the room via Rooms->Transform rooms-> Rotate rooms clockwise

Result:
<img width="310" alt="image" src="https://github.com/user-attachments/assets/a1dc5cb1-87b3-4596-9507-0be3c753df3a">

**Comment by Nickelony** [comment]
Just tested it on 1.7.1, I sadly cannot replicate it:

https://github.com/user-attachments/assets/332b4a5e-4023-4c77-8fe1-81e3978c277b
