### ISSUE TITLE
TE-NGLE  Slope collision triggers dosen't work

### ISSUE THREAD

**Issue by TiTiMartos** [MontyTRC89/Tomb-Editor#938]
Hi, in TRNE version the Flip effect  "Collision set... Slope collision...",  F310 to F329
 dosen't work, is posible to revise?
Thanks.

**Comment by Lwmte** [comment]
Yes, collision "triggers" in NGLE were not actual triggers, they were a hack to override floor collision. This functionality is reproduced with ghost blocks.
