### ISSUE TITLE
TE - Textures: Adding new formats (.psp, .pspimage, .xcf...)

### ISSUE THREAD

**Issue by illyaine** [MontyTRC89/Tomb-Editor#943]
Add textures in new formats

I am currently testing the graphics program Paint Shop Pro.
It would therefore of course be good if the main format were also supported by the program.

Corel Paint Shop Pro -> .pspimage, .psp etc

Or also from Gimp -> .XCF

With the .psd format this is also very practical, if you change something, this is immediately changed in the TE.

Attached is a Paint Shop Pro file.
http://devxs.de/TEN/Image2.pspimage

**Comment by Nickelony** [comment]
#546 

The `.PSP` / `.PSPIMAGE` formats seem to be closed-source, much like `.AFPHOTO` files.
We can't add support for something that doesn't have a library for reading such files.
