### ISSUE TITLE
TE - Ghost block size, also make the width customizable

### ISSUE THREAD

**Issue by illyaine** [MontyTRC89/Tomb-Editor#948]
Currently, you can only adjust the height of the Ghost Block.
It would therefore be practical if this could also be done in width.
This would allow you to make certain objects “walkable” or set a collision and much more.

**Comment by Nickelony** [comment]
This is not possible as a Ghost Block is just a fake alternative height value for a single sector's floordata. It's not an object / entity on its own when compiled into the game.
We are planning to implement something like this in the far future: #731 
As for Ghost Blocks, they will stay as they are (with the possibility to have diagonal ghost blocks in the future).
