### ISSUE TITLE
Unable to import animations

### ISSUE THREAD

**Issue by TrainWrack** [MontyTRC89/Tomb-Editor#970]
I am unable to import animations using the latest development version. The animation exports and there is an xml file. But when I go to import it, it gives me an error:

![image](https://github.com/user-attachments/assets/4c529ad5-f35e-495b-a723-52f205d80f1b)

To replicate, export an animation and then try to import it.

**Comment by Lwmte** [comment]
I can't reproduce it. Provide a wad which causes the bug.

**Comment by Lwmte** [comment]
Fixed
